apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet
  namespace: marketing
spec:
  selector:
    matchLabels:
      app: intranet
  replicas: 3
  template:
    metadata:
      labels:
        app: intranet
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80